global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'archipelago'
    replica: 'prometheus-1'

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 30s

  - job_name: 'minio'
    metrics_path: /minio/prometheus/metrics
    scheme: http
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 30s